# This file was generated by GoReleaser. DO NOT EDIT.
class Twtxt < Formula
  desc "📕 twtxt is a Self-Hosted, Twitter™-like Decentralised microBlogging
platform. No ads, no tracking, your content, your data!
"
  homepage "https://github.io/prologic/twtxt"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/prologic/twtxt/releases/download/0.1.1/twtxt_0.1.1_darwin_amd64.tar.gz"
    sha256 "9e5e1e063b8218ee5236c5490b340f4e9a3ab09778571c430a1ed1b974403d53"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/prologic/twtxt/releases/download/0.1.1/twtxt_0.1.1_linux_amd64.tar.gz"
      sha256 "2811288a86434b6793cc8dd2d011ec156c9fb3abccd4d712ba14ed6fc5ab2b96"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prologic/twtxt/releases/download/0.1.1/twtxt_0.1.1_linux_arm64.tar.gz"
        sha256 "48a326a35806de06eb768493b0ac14fa186a5267eafa52d6051377a1386f6034"
      else
        url "https://github.com/prologic/twtxt/releases/download/0.1.1/twtxt_0.1.1_linux_armv6.tar.gz"
        sha256 "e8f783ffdbe0b791632c142195aed1cd76970b63f0cef6a8a8b61e521331ae0b"
      end
    end
  end

  def install
    bin.install "twt"
  end
end
